const Soyjack = require('./src/Soyjack.js');

const soy = new Soyjack([
    234234142423421324214,
    123442421423421412412,
    123442421423421412412
]);

soy.getSoyJack('Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean lacinia cursus fringilla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed non orci mauris. Aenean mattis eget neque at cursus. Vestibulum sed sem at augue auctor condimentum. In urna enim, volutpat eu viverra quis, porta quis eros. Phasellus non diam in orci volutpat volutpat. Donec elementum leo et sem consectetur ullamcorper. Vestibulum sagittis risus velit, nec tincidunt lorem maximus non Vestibulum non finibus enim. Nullam at vulputate neque. Sed scelerisque augue ligula, et accumsan nulla posuere eleifend. Proin sed leo et urna interdum dapibus. Pellentesque sollicitudin ex enim, et consectetur dui aliquet ac. Nam porta gravida ante, sit amet pharetra justo finibus id. Etiam sollicitudin dictum mollis. Nulla facilisi. Aliquam tincidunt id lorem sed congue. Praesent egestas lacinia metus, id congue tellus ornare in. In blandit libero vel vestibulum convallis. Integer convallis pretium nibh sed pretium.Suspendisse cursus tellus ipsum, quis laoreet velit mattis quis. Nam placerat quis quam a vehicula. Pellentesque at purus ut dolor molestie tincidunt. Aliquam eu orci tincidunt, dignissim sem quis, euismod massa. Curabitur nec ligula a arcu rutrum consectetur non nec metus. Mauris pretium metus viverra ex ullamcorper lacinia. Suspendisse potenti. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla tincidunt dolor in porta suscipit.Vivamus fringilla mi id orci viverra iaculis. Etiam vel mauris luctus neque mollis semper sit amet quis ipsum. Cras eget mollis tortor. Vestibulum molestie urna justo, a aliquam mi ornare vitae. Quisque mollis congue felis non fringilla. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ullamcorper ex ac ex molestie, vel bibendum elit vulputate. Mauris iaculis ipsum velit, sed lobortis ligula laoreet eget. Duis maximus, elit in pulvinar blandit, nibh leo interdum nunc, a iaculis nisi lorem at leo.Nullam pretium augue erat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean tincidunt sagittis metus vel efficitur. Vestibulum hendrerit mauris tellus, sit amet rutrum nisl elementum a. Maecenas dapibus rutrum ante molestie pharetra. Nulla ac nulla quam. Sed sollicitudin viverra facilisis. Phasellus nec suscipit tellus. Vivamus est nunc, egestas vel felis tempus, cursus aliquam dui. Nulla laoreet diam ut tempor placerat. Vestibulum tincidunt elementum metus');
console.log(soy.message);